yolo_model:

  config_file:
    name: yolov2-tiny-voc.cfg
  weight_file:
    name: yolov2-tiny-voc_3000.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - fire
      - injury
      - robbery
 
